include: [project_templates.yml]

name: QuickWorkouts

packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 0.1.0

targets:
  QuickWorkouts:
    templates: [Target]
    dependencies:
      - target: CoreLogic
      - target: QuickWorkoutsList
      - target: DomainEntities
      - target: CorePersistence
      - target: CoreInterface
      - target: QuickWorkoutForm
      - target: RunningTimer
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: CoreLogicUnitTests
        - name: CoreInterfaceUnitTests
        - name: CorePersistenceUnitTests
        - name: QuickWorkoutFormUnitTests
        - name: RunningTimerUnitTests
        - name: QuickWorkoutsListUnitTests

  DomainEntities:
    templates: [CoreFramework]

  CoreLogic:
    templates: [CoreFramework]
    dependencies:
      - package: ComposableArchitecture

  CoreLogicUnitTests:
    templates: [CoreUnitTests]
    templateAttributes:
      frameworkName: CoreLogic
    dependencies:
      - package: ComposableArchitecture

  CoreInterface:
    templates: [CoreFramework]
    dependencies: 
      - target: DomainEntities
      - target: CoreLogic

  CoreInterfaceUnitTests:
    templates: [CoreUnitTests]
    templateAttributes:
      frameworkName: CoreInterface

  CorePersistence:
    templates: [CoreFramework]
    dependencies:
      - target: DomainEntities

  CorePersistenceUnitTests:
    templates: [CoreUnitTests]
    templateAttributes:
      frameworkName: CorePersistence

  QuickWorkoutForm:
    templates: [ScreenFramework]
    dependencies:
      - target: CorePersistence

  QuickWorkoutFormUnitTests:
    templates: [ScreenUnitTests]
    templateAttributes:
      frameworkName: QuickWorkoutForm
    dependencies:
      - target: CorePersistence

  RunningTimer:
    templates: [ScreenFramework]
    dependencies:
      - target: CorePersistence

  RunningTimerUnitTests:
    templates: [ScreenUnitTests]
    templateAttributes:
      frameworkName: RunningTimer

  QuickWorkoutsList:
    templates: [ScreenFramework]
    dependencies:
      - target: RunningTimer
      - target: QuickWorkoutForm
      - target: CorePersistence

  QuickWorkoutsListUnitTests:
    templates: [ScreenUnitTests]
    templateAttributes:
      frameworkName: QuickWorkoutsList
    dependencies:
      - target: RunningTimer
      - target: QuickWorkoutForm
      - target: CorePersistence
