include: [project_templates.yml]

name: Timer Wiz

fileGroups:
  - project.yml
  - project_templates.yml
  - .github

packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 0.10.0

targets:
  Timer Wiz:
    templates: [Target]
    dependencies:
      - target: CoreLogic
      - target: QuickWorkoutsList
      - target: DomainEntities
      - target: CorePersistence
      - target: CoreInterface
      - target: QuickWorkoutForm
      - target: RunningTimer
      - target: WorkoutSettings
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: CoreLogicUnitTests
        - name: CoreInterfaceUnitTests
        - name: CorePersistenceUnitTests
        - name: QuickWorkoutFormUnitTests
        - name: RunningTimerUnitTests
        - name: QuickWorkoutsListUnitTests
        - name: WorkoutSettingsUnitTests

  DomainEntities:
    templates: [CoreFramework]

  CoreLogic:
    templates: [CoreFramework]
    dependencies:
      - package: ComposableArchitecture

  CoreLogicUnitTests:
    templates: [CoreUnitTests]
    templateAttributes:
      frameworkName: CoreLogic
    dependencies:
      - package: ComposableArchitecture

  CoreInterface:
    templates: [CoreFramework]
    dependencies: 
      - target: DomainEntities
      - target: CoreLogic

  CoreInterfaceUnitTests:
    templates: [CoreUnitTests]
    templateAttributes:
      frameworkName: CoreInterface

  CorePersistence:
    templates: [CoreFramework]
    dependencies:
      - target: DomainEntities

  CorePersistenceUnitTests:
    templates: [CoreUnitTests]
    templateAttributes:
      frameworkName: CorePersistence

  QuickWorkoutForm:
    templates: [ScreenFramework]
    dependencies:
      - target: CorePersistence

  QuickWorkoutFormUnitTests:
    templates: [ScreenUnitTests]
    templateAttributes:
      frameworkName: QuickWorkoutForm
    dependencies:
      - target: CorePersistence

  RunningTimer:
    templates: [ScreenFramework]
    dependencies:
      - target: CorePersistence

  RunningTimerUnitTests:
    templates: [ScreenUnitTests]
    templateAttributes:
      frameworkName: RunningTimer

  QuickWorkoutsList:
    templates: [ScreenFramework]
    dependencies:
      - target: RunningTimer
      - target: QuickWorkoutForm
      - target: CorePersistence
      - target: WorkoutSettings

  QuickWorkoutsListUnitTests:
    templates: [ScreenUnitTests]
    templateAttributes:
      frameworkName: QuickWorkoutsList
    dependencies:
      - target: RunningTimer
      - target: QuickWorkoutForm
      - target: CorePersistence
      - target: WorkoutSettings

  WorkoutSettings:
    templates: [ScreenFramework]

  WorkoutSettingsUnitTests:
    templates: [ScreenUnitTests]
    templateAttributes:
      frameworkName: WorkoutSettings

schemes: 
  CoreLogic:
    templates: 
      - FrameworkScheme
  QuickWorkoutsList:
    templates: 
      - FrameworkScheme
  DomainEntities:
    build:
      targets:
        DomainEntities: all
    run:
  CorePersistence:
    templates: 
      - FrameworkScheme
  CoreInterface:
    templates: 
      - FrameworkScheme
  QuickWorkoutForm:
    templates: 
      - FrameworkScheme
  RunningTimer:
    templates: 
      - FrameworkScheme
