include: [project_templates.yml]

name: QuickWorkouts

fileGroups:
  - project.yml
  - project_templates.yml
  - .github

packages:
  DomainEntities:
    path: InternalFrameworks/Core/DomainEntities
  CorePersistence:
    path: InternalFrameworks/Core/CorePersistence
  CoreLogic:
    path: InternalFrameworks/Core/CoreLogic
  CoreInterface:
    path: InternalFrameworks/Core/CoreInterface
  QuickWorkoutsList:
    path: InternalFrameworks/Screens/QuickWorkoutsList
  QuickWorkoutForm:
    path: InternalFrameworks/Screens/QuickWorkoutForm
  RunningTimer:
    path: InternalFrameworks/Screens/RunningTimer
  WorkoutSettings:
    path: InternalFrameworks/Screens/WorkoutSettings

  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 0.10.0

targets:
  QuickWorkouts:
    templates: [Target]
    dependencies:
      - package: CoreLogic
      - package: CorePersistence
      - package: CoreInterface
      - package: DomainEntities
      - package: QuickWorkoutsList
      - package: QuickWorkoutForm
      - package: RunningTimer
      - package: WorkoutSettings
    scheme:
      gatherCoverageData: true
