include: [project_templates.yml]

name: Timer Wiz

fileGroups:
  - project.yml
  - project_templates.yml
  - .github

packages:
  DomainEntities:
    path: Packages/Core/DomainEntities
  CorePersistence:
    path: Packages/Core/CorePersistence
  CoreLogic:
    path: Packages/Core/CoreLogic
  CoreInterface:
    path: Packages/Core/CoreInterface
  QuickWorkoutsList:
    path: Packages/Screens/QuickWorkoutsList
  QuickWorkoutForm:
    path: Packages/Screens/QuickWorkoutForm
  RunningTimer:
    path: Packages/Screens/RunningTimer
  WorkoutSettings:
    path: Packages/Screens/WorkoutSettings

  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 0.10.0

targets:
  Timer Wiz:
    templates: [Target]
    dependencies:
      - package: CoreLogic
      - package: CorePersistence
      - package: CoreInterface
      - package: DomainEntities
      - package: QuickWorkoutsList
      - package: QuickWorkoutForm
      - package: RunningTimer
      - package: WorkoutSettings
    scheme:
      gatherCoverageData: true

  Timer Wiz Watch:
    templates: [watchOS-Target]
    dependencies:
      - target: Timer Wiz Watch Extension

  Timer Wiz Watch Extension:
    templates: [watchOS-Extension]
    dependencies:
      - package: CoreLogic
      - package: CorePersistence
      - package: CoreInterface
      - package: DomainEntities
      - package: QuickWorkoutsList
      - package: QuickWorkoutForm
      - package: RunningTimer
      - package: WorkoutSettings

