include: [project_templates.yml]

name: QuickWorkouts

fileGroups:
  - project.yml
  - project_templates.yml
  - .github

packages:
  DomainEntities:
    path: InternalFrameworks/Core/DomainEntities
  CoreLogic:
    path: InternalFrameworks/Core/CoreLogic
  CorePersistence:
    path: InternalFrameworks/Core/CorePersistence

  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 0.10.0

targets:
  QuickWorkouts:
    templates: [Target]
    dependencies:
      - target: CoreLogic2
      - target: QuickWorkoutsList
      - target: CoreInterface
      - target: QuickWorkoutForm
      - target: RunningTimer
      - target: WorkoutSettings
      - package: CorePersistence
      - package: DomainEntities
      - package: CoreLogic
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: CoreLogic2UnitTests
        - name: CoreInterfaceUnitTests
        - name: QuickWorkoutFormUnitTests
        - name: RunningTimerUnitTests
        - name: QuickWorkoutsListUnitTests
        - name: WorkoutSettingsUnitTests

  CoreLogic2:
    templates: [CoreFramework]
    dependencies:
      - package: ComposableArchitecture

  CoreLogic2UnitTests:
    templates: [CoreUnitTests]
    templateAttributes:
      frameworkName: CoreLogic2
    dependencies:
      - package: ComposableArchitecture

  CoreInterface:
    templates: [CoreFramework]
    dependencies:
      - package: DomainEntities
      - package: CoreLogic
      - target: CoreLogic2

  CoreInterfaceUnitTests:
    templates: [CoreUnitTests]
    templateAttributes:
      frameworkName: CoreInterface

  QuickWorkoutForm:
    templates: [ScreenFramework]
    dependencies:
      - package: CorePersistence

  QuickWorkoutFormUnitTests:
    templates: [ScreenUnitTests]
    templateAttributes:
      frameworkName: QuickWorkoutForm
    dependencies:
      - package: CorePersistence

  RunningTimer:
    templates: [ScreenFramework]
    dependencies:
      - package: CorePersistence

  RunningTimerUnitTests:
    templates: [ScreenUnitTests]
    templateAttributes:
      frameworkName: RunningTimer

  QuickWorkoutsList:
    templates: [ScreenFramework]
    dependencies:
      - target: RunningTimer
      - target: QuickWorkoutForm
      - target: WorkoutSettings
      - package: CorePersistence

  QuickWorkoutsListUnitTests:
    templates: [ScreenUnitTests]
    templateAttributes:
      frameworkName: QuickWorkoutsList
    dependencies:
      - target: RunningTimer
      - target: QuickWorkoutForm
      - target: WorkoutSettings
      - package: CorePersistence

  WorkoutSettings:
    templates: [ScreenFramework]

  WorkoutSettingsUnitTests:
    templates: [ScreenUnitTests]
    templateAttributes:
      frameworkName: WorkoutSettings

schemes: 
  CoreLogic2:
    templates:
      - FrameworkScheme
  QuickWorkoutsList:
    templates: 
      - FrameworkScheme
  CoreInterface:
    templates: 
      - FrameworkScheme
  QuickWorkoutForm:
    templates: 
      - FrameworkScheme
  RunningTimer:
    templates: 
      - FrameworkScheme
