name: deploy-testflight
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force XCode 12
        run: sudo xcode-select -switch /Applications/Xcode_12.app
      - name: Install gpg
        run: brew install gnupg
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: |
          chmod 755 .github/secrets/decrypt_secrets.sh
          ./.github/secrets/decrypt_secrets.sh
      - name: Archiving project
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: |
          chmod 755 .github/scripts/archive_app.sh
          ./.github/scripts/archive_app.sh
      - name: Exporting .ipa
        run: |
          chmod 755 .github/scripts/export_ipa.sh
          ./.github/scripts/export_ipa.sh
      - name: Publishing app
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        run: |
          chmod 755 .github/scripts/publish_testflight.sh
          ./.github/scripts/publish_testflight.sh
