name: testing
on: [push]

jobs:
  test:
    name: Testing iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force XCode 12
        run: sudo xcode-select -switch /Applications/Xcode_12.app
      - name: Testing iOS app
        run: |
          xcodebuild -project ./WorkoutTimer.xcodeproj -list
          chmod 755 .github/scripts/test_app.sh 
          exec ./.github/scripts/test_app.sh
